grails-app/domain/ru/srms/larp/platform/game/resources/ResourceInstance.groovy
package ru.srms.larp.platform.game.resources

import ru.srms.larp.platform.game.Game
import ru.srms.larp.platform.game.InGameStuff
import ru.srms.larp.platform.game.Titled
import ru.srms.larp.platform.game.character.GameCharacter

/**
 * E.g. bank account, personal mana bar, etc.
 */
class ResourceInstance implements InGameStuff, Titled {

  String title
  String identifier
  ResourceOrigin origin
  Boolean transferable = false
  Boolean ownerEditable = false
  GameCharacter owner
  Double value = 0

  Double minValue
  Double maxValue

  static belongsTo = [type: GameResource]

  static constraints = {
    owner nullable: true
    origin nullable: true
    title maxSize: 64, unique: 'type'
    identifier maxSize: 64, unique: 'type'
    minValue nullable: true
    maxValue nullable: true
    value validator: { val, obj ->
      if(obj.minValue != null && val < obj.minValue)
        return 'resourceInstance.value.ltMinValue'
      if(obj.maxValue != null && val > obj.maxValue)
        return 'resourceInstance.value.gtMaxValue'
    }
  }

  public static def getAllByGame(Game game) {
    ResourceInstance.findAll("from ResourceInstance as res WHERE res.type.game=? ORDER BY res.type.title, res.title", [game])
  }

  public def getTransferLogs() {
    TransferLogEntry.findAllBySourceOrTarget(this, this);
  }

  public def getPeriodicRules() {
    ResourcePeriodicRule.findAllByTarget(this)
  }

  public static def groupByType(List<ResourceInstance> list) {
    Map<GameResource, List<ResourceInstance>> result = [:]
    list.each {
      result.putIfAbsent(it.type, [])
      result.get(it.type).add(it)
    }
    result
  }

  def beforeValidate() {
    this.value = Math.round(this.value * 100) / 100
  }

  String getFullId() {
    def result = this.identifier
    if(this.type.identifierTitle)
      result = "${this.type.identifierTitle}${result}"
    return result
  }

  @Override
  Game extractGame() {
    return type.game
  }

  @Override
  String extractTitle() {
    return type.title+ ": " + title
  }
}

grails-app/controllers/ru/srms/larp/platform/game/resources/ResourceInstanceController.groovy
package ru.srms.larp.platform.game.resources

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import ru.srms.larp.platform.BaseModuleController
import ru.srms.larp.platform.ResourceService
import ru.srms.larp.platform.game.Game

import static org.springframework.http.HttpStatus.*

@Secured(['IS_AUTHENTICATED_REMEMBERED'])
@Transactional(readOnly = true)
class ResourceInstanceController extends BaseModuleController {

  ResourceService resourceService

  static allowedMethods = [save: "POST", update: "POST", changeValue: "POST", transfer: "POST"]

  def show(ResourceInstance resource) {
    withModule {
      respond resourceService.getResourceInstance(resource)
    }
  }

  def create() {
    withModule {
      if (!GameResource.exists(params.typeId))
        throw new Exception("Неверный тип ресурсы")
      def type = GameResource.get(params.typeId)
      respond resourceService.createResourceInstance(type)
    }
  }

  def edit(ResourceInstance resource) {
    withModule {
      respond resourceService.editResourceInstance(resource)
    }
  }

  @Transactional
  def changeValue() {
    withModule {
      def resource = ResourceInstance.get(params.id)
      resource.properties['value'] = params
      if (validateData(resource, 'show')) {
        resourceService.updateResourceValue(resource)
        respondChange('Вы успешно изменили значение', OK,
            [action: 'show', id: resource.id])
      }
    }
  }

  @Transactional
  def transfer(TransferData data) {
    withModule {
      def source = ResourceInstance.get(params.id)
      data.source = source
      if (!data.validate()) {
        respond source, model: [transferData: data], view: 'show'
        return
      }
      resourceService.transfer(data)
      respondChange('Перевод успешно осуществлен', OK,
          [action: 'show', id: source.id])
    }
  }

  @Transactional
  def save(ResourceInstance resource) {
    withModule {
      if (validateData(resource, 'create')) {
        resourceService.saveResourceInstance(resource)
        respondChange('Экземпляр ресурса успешно создан', CREATED,
            [controller: 'GameResource', action: 'show', id: resource.type.id])
      }
    }
  }

  @Transactional
  def update() {
    withModule {
      // saving old params to change permission correctly
      def resource = ResourceInstance.get(params.id)
      def oldResource = new HashMap<>(resource.properties)
      resource.properties = params

      if (validateData(resource, 'edit')) {
        resourceService.saveResourceInstance(resource, oldResource)
        respondChange('Экземпляр ресурса обновлен', OK,
            [controller: 'GameResource', action: 'show', id: resource.type.id])
      }
    }
  }

  @Transactional
  def delete(ResourceInstance resource) {
    withModule {
      if (validateData(resource)) {
        resourceService.deleteResourceInstance(resource)
        respondChange('Экземпляр ресурса удален', NO_CONTENT,
            [controller: 'GameResource', action: 'show', id: resource.type.id])
      }
    }
  }

  @Override
  protected Game.GameModule module() {
    return Game.GameModule.RESOURCES
  }
}

grails-app/views/resourceInstance/_available.gsp
<%@ page import="ru.srms.larp.platform.game.resources.ResourceInstance" %>
<section class="ui pilled segment">
  <div class="ui blue ribbon label">Ресурсы</div>
  <ul class="property-list">
    <g:each in="${items}" var="item">
      <li>
        ${item.key.title}
        <g:set var="resList" value="${item.value as List<ResourceInstance>}"/>
        <ul>
          <g:each in="${resList}" var="res">
            <li>
              <ingame:link resource="${res}" action="show">${res.title}</ingame:link>
              (${res.value}<g:if test="${res.type.measure}"> ${res.type.measure}</g:if>)
            </li>
          </g:each>
        </ul>
      </li>
    </g:each>
  </ul>
</section>

grails-app/views/resourceInstance/_form.gsp
<%@ page import="ru.srms.larp.platform.game.resources.ResourceInstance; ru.srms.larp.platform.game.character.GameCharacter" %>
<g:set var="subject" value="${subject as ResourceInstance}"/>

<div class="ui three fields">
  <div class="${hasErrors(bean: subject, field: 'title', 'error')} required field">
    <label for="title">Название</label>
    <g:field type="text" name="title" required="" value="${subject?.title}"/>
    <div class="ui pointing label">Максимум 64 символа. Должно быть уникальным в рамках типа ресурса.</div>
  </div>

  <div class="${hasErrors(bean: subject, field: 'identifier', 'error')} required field">
    <label for="identifier">Идентификатор</label>
    <g:field type="text" name="identifier" required="" value="${subject?.identifier}"/>
    <div class="ui pointing label">Максимум 64 символа. Должен быть уникальным в рамках типа ресурса.</div>
  </div>

  <div class="${hasErrors(bean: subject, field: 'value', 'error')} required field">
    <label for="value">Количество ресурса</label>
    <g:field type="text" name="value" required="" value="${subject?.value}"/>
  </div>
</div>

<div class="ui three fields">
  <div class="${hasErrors(bean: subject, field: 'minValue', 'error')} field">
    <label for="minValue">Минимальное значение</label>
    <g:field type="text" name="minValue" value="${subject?.minValue != null ? subject.minValue : subject?.type?.minValue}"/>
    <div class="ui pointing label">Оставьте пустым, если минимальное значение не нужно.</div>
  </div>

  <div class="${hasErrors(bean: subject, field: 'maxValue', 'error')} field">
    <label for="maxValue">Максимальное значение</label>
    <g:textField name="maxValue" value="${subject?.maxValue != null ? subject.maxValue : subject?.type?.maxValue}"/>
    <div class="ui pointing label">Оставьте пустым, если максимальное значение не нужно.</div>
  </div>
</div>

<div class="ui three fields">
<div class="${hasErrors(bean: subject, field: 'origin', 'error')} field">
  <label for="origin.id">Источник</label>
  <g:select name="origin.id" from="${subject.type.origins}" value="${subject.origin?.id}"
            class="dropdown" data-placeholder="Выберите источник"
            optionKey="id" optionValue="title" noSelection="${['null': '']}"/>
</div>

<div class="${hasErrors(bean: subject, field: 'owner', 'error')} field">
  <label for="owner.id">Владелец</label>
  <g:select name="owner.id" from="${GameCharacter.findAllByGame(params.game)}" class="dropdown"
            data-placeholder="Выберите владельца"
            value="${subject.owner?.id}" optionKey="id" noSelection="${['null': '']}"/>
  <div class="ui pointing label">Игрок, управляющий ресурсом. Можно оставить пустым - это будет мастерский ресурс.</div>
</div>
</div>


<div class="${hasErrors(bean: subject, field: 'transferable', 'error')} inline field">
  <div class="ui toggle checkbox">
    <g:checkBox name="transferable" value="${subject?.transferable}"/>
    <label for="transferable">Можно переводить средства?</label>
  </div>
</div>

<div class="${hasErrors(bean: subject, field: 'ownerEditable', 'error')} inline field">
  <div class="ui toggle checkbox">
    <g:checkBox name="ownerEditable" value="${subject?.ownerEditable}"/>
    <label for="ownerEditable">Игрок может менять значение напрямую?</label>
  </div>
</div>

<g:hiddenField name="type.id" id="type" value="${subject.type.id}"/>

grails-app/views/resourceInstance/_transferLog.gsp
<g:set var="outcome" value="${log.source == parent}"/>
<g:set var="relatedResourceName" value="${outcome ? log.targetName : log.sourceName}"/>

<div class="item" title="${outcome ? "Исходящий" : "Входящий"}">
  <g:if test="${outcome}">
    <i class="red arrow up icon"></i>
  </g:if>
  <g:else>
    <i class="green arrow down icon"></i>
  </g:else>

  <div class="content">
    <div class="header">
      ${log.value} ${log.target ? log.target.type.measure : log.source ? log.source.type.measure : ""}
    </div>

    <div class="description"><g:render template="/shared/date" model="[date: log.date]"/></div>
    ${outcome ? "Получатель" : "Отправитель"}: ${relatedResourceName}

    <g:if test="${log.comment}">
      <div class="comment">Комментарий: ${log.comment}</div>
    </g:if>
  </div>
</div>

grails-app/views/resourceInstance/create.gsp
<%@ page import="ru.srms.larp.platform.game.resources.ResourceInstance;" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="mainWithActions">
  <g:set var="subject" value="${resourceInstanceInstance as ResourceInstance}"/>
  <g:set var="title" value="Создание ресурса типа ${subject.type.title}"/>
  <title>${title}</title>
</head>

<body>
<content tag="actions">
  <ingame:link class="item" action="show" resource="${subject.type}">
    <i class="cancel grey icon"></i> Отмена</ingame:link>
</content>

<content tag="content">
  <g:render template="/shared/fromErrors" bean="${subject}" var="subject"/>
  <ingame:form class="ui form" url="[resource: subject, action: 'save']">
    <g:render template="form"/>
    <ui:submit class="primary" icon="add">Сохранить</ui:submit>
  </ingame:form>
</content>

</body>
</html>

grails-app/views/resourceInstance/edit.gsp
<%@ page import="ru.srms.larp.platform.game.resources.ResourceInstance; org.springframework.validation.FieldError" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="mainWithActions">
  <g:set var="subject" value="${resourceInstanceInstance as ResourceInstance}"/>
  <g:set var="title" value="Редактирование ресурса ${subject.fullId}"/>
  <title>${title}</title>
</head>

<body>
<content tag="actions">
  <ingame:link class="item" action="show" resource="${subject.type}">
    <i class="cancel grey icon"></i> Отмена</ingame:link>

  <ingame:link class="item" controller="ResourcePeriodicRule" action="create"
               params="['target.id': subject.id]">
    <i class="green wait icon"></i> Создать периодическое правило</ingame:link>
</content>

<content tag="content">
  <g:render template="/shared/fromErrors" bean="${subject}" var="subject"/>
  <ingame:form class="ui form" url="[resource: subject, action: 'update']">
    <g:render template="form"/>
    <g:hiddenField name="version" value="${subject?.version}"/>
    <ui:submit icon="checkmark">Сохранить</ui:submit>
  </ingame:form>

  <section class="ui pilled segment">
    <div class="ui blue ribbon label">Правила периодического изменения</div>

    <div class="ui hidden divider"></div>
    <g:if test="${!subject.periodicRules.size()}">
      <ui:message type="info">Список правил пуст.</ui:message>
    </g:if>
    <div class="ui grid">
      <div class="seven wide column">
        <div class="ui middle aligned selection divided list">
          <g:each in="${subject.periodicRules}" var="rule">
            <g:render template="/resourcePeriodicRule/show" model="[item: rule]"/>
          </g:each>
        </div>
      </div>
    </div>
  </section>
</content>
</body>
</html>

grails-app/views/resourceInstance/show.gsp
<%@ page import="ru.srms.larp.platform.game.resources.ResourceInstance" %>
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="mainWithActions">
  <g:set var="subject" value="${resourceInstanceInstance as ResourceInstance}"/>
  <g:set var="title" value="${subject.title}"/>
  <title>${title}</title>
</head>

<body>
<content tag="actions">
  <g:link mapping="playAs" params="[gameAlias: params.gameAlias, charAlias: params.charAlias]"
          class="item"><i
      class="arrow left grey icon"></i> Назад</g:link>
</content>

<content tag="content">
  <div class="ui two column stackable grid">
    <div class="seven wide column">
      <section class="ui pilled segment">
        <div class="ui blue ribbon label">${subject.fullId}</div>
        <div class="ui hidden divider"></div>

        <sec:permitted object="${subject}" permission="write">
          <g:render template="/shared/fromErrors" bean="${subject}" var="subject"/>
          <ingame:form class="ui form" url="[resource: subject, action: 'changeValue']"
                       method="post">

            <div class="${hasErrors(bean: subject, field: 'value', 'error')} inline required field">
              <label for="value">Значение:</label>
              <g:textField name="value" required="" value="${subject?.value}"/>
              <g:if test="${subject.type.measure}">${subject.type.measure}</g:if>
            </div>
            <ui:submit name="update" icon="checkmark">Сохранить</ui:submit>
          </ingame:form>
        </sec:permitted>
        <sec:notPermitted object="${subject}" permission="write">
          <div style="padding-top: 10px"></div>
          <strong>
            Текущее значение: <span class="ui violet circular label">${subject.value}</span>
            <g:if test="${subject.type.measure}">${subject.type.measure}</g:if>
          </strong>
        </sec:notPermitted>
        <g:if test="${subject.minValue != null}">
          <div>Минимальное значение: <strong>${subject.minValue}</strong></div>
        </g:if>
        <g:if test="${subject.maxValue != null}">
          <div>Максимальное значение: <strong>${subject.maxValue}</strong></div>
        </g:if>
      </section>
    </div>

    <section class="nine wide column">
      <sec:permitted object="${subject}" permission="create">
        <section class="ui pilled segment">
          <div class="ui blue ribbon label">Произвести перевод</div>

          <div class="ui hidden divider"></div>

          <g:render template="/shared/fromErrors" bean="${transferData}" var="subject"/>
          <ingame:form class="ui form" url="[resource: subject, action: 'transfer']" method="post">
            <div class="fields">
              <div
                  class="${hasErrors(bean: transferData, field: 'transferValue', 'error')} required field">
                <label for="value">Количество:</label>
                <g:textField name="transferValue" required=""
                             placeholder="0 ${subject.type.measure}"
                             value="${transferData?.transferValue}"/>
              </div>

              <div
                  class="${hasErrors(bean: transferData, field: 'transferTargetId', 'error')} required field">
                <label for="value">Кому:</label>
                <g:textField name="transferTargetId" required=""
                             placeholder="${subject.type.identifierTitle}"
                             value="${transferData?.transferTargetId}"/>
              </div>
            </div>
            <div
                    class="${hasErrors(bean: transferData, field: 'comment', 'error')} field">
              <label for="value">Комментарий:</label>
              <g:textField name="comment"
                          placeholder="Текст комментария"
                          value="${transferData?.comment}"/>
              <div class="ui pointing label">Максимум 128 символов. Можно оставить пустым.</div>
            </div>

            <ui:submit name="send" icon="right arrow">Отправить</ui:submit>
          </ingame:form>
        </section>
      </sec:permitted>

      <section class="ui pilled segment">
        <div class="ui blue ribbon label">История переводов</div>

        <div class="ui selection list">
          <g:each in="${subject.transferLogs}" var="log">
            <g:render template="transferLog" model="[log: log, parent: subject]"/>
          </g:each>
          <g:if test="${subject.transferLogs.size() == 0}">
            <ui:message type="info">История переводов пуста</ui:message>
          </g:if>
        </div>
      </section>
  </div>
</content>
</body>
</html>